### ISSUE TITLE
Bug with 2-3 rows

### ISSUE THREAD

**Issue by matteopiccioni** [MichiganLabs/AnimatingTableViewHeader#1]
Hello,
if the tableview has 2-3 rows, the header will not expand

**Comment by johndelong** [comment]
Ah, good observation! In that scenario we shouldn't let the header collapse at all (since all of the content can actually fit within the `scrollView`). I'll update the example project soon to account for that scenario.

**Comment by matteopiccioni** [comment]
Thank you very much :)
